### PR TITLE
Adding support for white-listing access public sources

### PR DESCRIPTION
**Pull request by Patrik-Netent**
Adding possibility to specify which sources that is allowed to access the public network by adding a variable:

```
variable allowed_public_networks {
  description = "The public networks that is allowed access to public_subnetwork"
  default = ["0.0.0.0/0"]
  type = list(string)
}

```

Also renaming firewall rule from `public_allow_all_inbound` to `public_allow_inbound`.

### CODE REVIEW

**Comment by autero1** [comment]
Thanks for the PR @Patrik-Netent. While I do agree that ability to restrict network access to the edge is necessary, I'm not 100% sure if this change would be in line with the original purpose of the access tiers: https://github.com/gruntwork-io/terraform-google-network/tree/master/modules/vpc-network#access-tier

The firewalls act as "Virtual Network ACLs" and have a fairly low priority (1000), so limiting access to `public` instances is as easy as tagging them with another tag/firewall with a higher priority and more restricted access. 

Would love a second opinion @robmorgan @yorinasub17

**Comment by Patrik-Netent** [comment]
I thought about making a separate PR with another suggestion as well. How about creating a firewall rule that is applied to the tag public_access_restricted?

**Comment by yorinasub17** [comment]
If we consider the principle of "Defense in Depth", it seems like being able to restrict the public networks at this level is a good idea. E.g if I misconfigure the firewall so that I forget to add the restrictive access, I want the reassurance that the default rule will protect me (assuming this is a necessary restriction you have for this particular VPC).

I think this change set is the right balance: the default allows all access, and 80% of use cases will be ok with that. For the remaining 20% that needs tighter access control, this change set provides the ability to modify the default.

**Comment by jbnjohnathan** [comment]
I like the ability to be able to restrict with source IP. However I like Patriks second suggestion better.

Right now the module gives access from any source IP to VMs with the tag "public". I think this should stay the same. It would then be easy for anyone viewing a VM to know, if the tag is "public", then any source IP is allowed.

I would prefer if the possibility of allowing only some source IP's are used in conjunction with a new tag, for example "public_restricted".
That way, for 80% of the use cases that want to allow from any, they can keep using the tag "public" knowing that any time they see it, it means any IP is allowed.
For the other 20%, they can use the tag "public_restricted". Upon seeing this tag they know that only some IP addresses are allowed, and can view the FW rules if they need to know exactly which ones.
I think that creates a nice mix of readability and security features.

**Comment by autero1** [comment]
> I think that creates a nice mix of readability and security features.

Agree with @jbnjohnathan. Again, while restricting access is important, the keyword `public` indicates public access. My earlier point was that even if you tag your instances with `public`, you can easily create a more restrictive firewall rule (with a higher priority) as part of your application to override the ingress rules.

**Comment by Patrik-Netent** [comment]
Created an alternate pull request with a suggestion of how the alternate path could be implemented.

**Comment by Patrik-Netent** [comment]
Closing this one since the other option was chosen instead.

**Pull request closed without merging**
