### PR TITLE
Fix: migrate terraform list to tolist to suport terraform v0.15

### PR DESCRIPTION
**Pull request by meabed**
Hey there,
Please find this simple fix to Migrate terraform list to tolist to suport terraform v0.15. #63
Reference: https://www.terraform.io/docs/language/functions/list.html
I have tested it and works as expected.
Thank you.

### CODE REVIEW

**Comment by robmorgan** [comment]
hi @meabed, thank you for your contribution. Do you know if this change modifies the Terraform state file after switching from `list` to `tolist`?

**Comment by meabed** [comment]
Yes, no changes to the state file after applying this changes.

**Comment by robmorgan** [comment]
@meabed okay thank you. We need to prioritise an upgrade to TF 0.14 first, however I'll keep this PR open in the meantime.

**Comment by meabed** [comment]
Thank you, it works for both 0.14 and 0.15.

**Comment by brianpham** [comment]
Tested this on our dev cluster and it seems to work. Thanks for the help @meabed

**Comment by meabed** [comment]
Would you be able to merge this soon :) Thanks!

**Comment by robmorgan** [comment]
@meabed could you check and see what the earliest version of Terraform was that supported the `tolist` function? I.e. were there versions before TF 0.14?

**Comment by meabed** [comment]
@robmorgan Thanks! 
it works fine on TF 0.12 / 0.13

image

**Comment by robmorgan** [comment]
Hi @meabed thanks for this. Do you know the specific version of 0.12 it was introduced in? The reason for this is that we currently target a minimum of [0.12.26](https://github.com/gruntwork-io/terraform-google-network/blob/master/main.tf#L5), so I need to check to see if we need to raise any of our constaints.

**Comment by meabed** [comment]
Hi @robmorgan - yes it was introduced here: https://github.com/hashicorp/terraform/releases/tag/v0.12.0-beta1
So it will work in all 0.12 versions. Thanks!

**Comment by meabed** [comment]
Hi @robmorgan thought this fell between the cracks and wanted to send a gentle reminder :) 
If this looks good and doesn't break the module it would great fo merge it 😊 
Thank you 🙏

**Comment by robmorgan** [comment]
@meabed sorry about the delay!

**Review by robmorgan — APPROVED** [review]

**Comment by robmorgan** [comment]
Released in https://github.com/gruntwork-io/terraform-google-network/releases/tag/v0.8.1

**Pull request merged**
